const projects = [
  {
    id: 1,
    title: "Plataforma de idiomas + IA",
    technologies: ["React","Python", "FastAPI", "GPT"],
    code: "Proyecto Privado",
    demoLink: null,
    description:"Este proyecto personal está diseñado para transformar el aprendizaje de idiomas mediante la integración de inteligencia artificial y herramientas interactivas. Utilizando React para el frontend, FastAPI para el backend y la API de GPT, ofrece una experiencia educativa innovadora y personalizada. Entre sus funcionalidades destacan las prácticas conversacionales con un chatbot impulsado por IA, que corrige y mejora la fluidez del usuario, además de un asistente virtual que responde preguntas sobre gramática, vocabulario y pronunciación. También incluye video lecciones, quizzes, tests con límite de tiempo, prácticas de reconocimiento de voz y evaluaciones dinámicas generadas por GPT que analizan las habilidades lingüísticas de forma adaptativa. Este proyecto combina tecnología y diseño centrado en el usuario para ofrecer una solución integral y efectiva en el aprendizaje de idiomas",
    githubLink: null,
    views: [
      "/ia.png",
    ],
    bannerImage: "/word.png",
    category: "Desarrollo web",
    videoUrl: "https://www.youtube.com/watch?v=iV9xeYhw_kI",
  },
  {
    id: 2,
    title: "ChatNexus GPT",
    technologies: ["React", "Auth0", "GPT", "OpenAI", "Tavily IA"],
    code: "Público",
    demoLink: "https://chat.agencianexusmarketing.com/",
    description:"Este proyecto desarrollado para Nexus Marketing IA integra una solución avanzada que combina autenticación segura, inteligencia artificial y una interfaz de usuario interactiva. Está construido sobre la base del Morphic Template de Next.js, lo que garantiza un rendimiento optimizado y una estructura escalable para el desarrollo. Utiliza Auth0 para proporcionar un acceso controlado y seguro a los usuarios registrados, asegurando la protección de datos y la confiabilidad en la autenticación.Además, se conecta con las APIs de OpenAI y Tavily IA, aprovechando sus capacidades para generar respuestas dinámicas e inteligentes en tiempo real. Las vistas están diseñadas para mostrar estas respuestas de manera eficiente, utilizando componentes altamente interactivos que aseguran una experiencia fluida y amigable para los usuarios.",
    githubLink: "https://github.com/T0ny-dev/morphic",
    bannerImage: "/nex.png",
    category: "Desarrollo web",
    videoUrl: "https://www.youtube.com/watch?v=nDG_uTtscEw?modestbranding=1&rel=0",
  },
  {
    id: 3,
    title: "Portal Desarrolladores LarnU",
    technologies: ["React", "CSS", "Firebase", "GitHub Actions", "Jest", "Agile", "MVP"],
    code: "Proyecto Privado",
    description:"Portal de desarrolladores LarnU: Participación activa en el desarrollo frontend, destacando la implementación de componentes reutilizables y estilizados. Se incluyeron pruebas funcionales y de integración para garantizar la calidad del producto, junto con despliegues automatizados utilizando GitHub Actions para CI/CD. La colaboración con equipos multidisciplinarios fue esencial, trabajando bajo metodologías ágiles para cumplir con tiempos estrictos y entregables mínimos viables (MVP), asegurando que el proyecto cumpliera con los estándares de calidad y funcionalidad requeridos.",
    bannerImage: "/LarnU.png",
    category: "Desarrollo web",
    videoUrl: "https://www.youtube.com/watch?v=N60lrbpIYOg?modestbranding=1&rel=0",
  },
  {
    id: 4,
    title: "Kouka Busquedor de evento en Chile",
    technologies: ["React", "NextJS", "CSS", "Firebase"],
    code: "Proyecto Privado",
    demoLink: "https://www.kuoka.cl/",
    description:"El proyecto  de portal de busquedas incluye la conexión con Firebase para gestionar datos en tiempo real, además de diseñar la interfaz de usuario y la identidad visual del portal. Se desarrolló un scrapper basado en ChatGPT que busca eventos en Chile y almacena la información en la base de datos, permitiendo mantener la plataforma actualizada. Adicionalmente, se implementó un buscador por términos que facilita a los usuarios encontrar eventos específicos de manera rápida y eficiente.",
    bannerImage: "/kouka.png",
    category: "Desarrollo web",
    videoUrl: "https://www.youtube.com/watch?v=j4e_OEaRzkk?modestbranding=1&rel=0",
  },
  {
    id: 5,
    title: "Api de datos USICAMM de certificados",
    technologies: ["JavaScript", "Node", "Express", "Onrender", "QR Code", "Python"],
    code: "Proyecto Privado",
    demoLink: "https://viewer-cert-usicamm.vercel.app/?id=1",
    description:"Se creó una vista validadora de certificados, donde los usuarios pueden verificar la autenticidad de un certificado mediante su ID único. Además, los datos del certificado, como el nombre del beneficiario, fecha de emisión y detalles relevantes, se muestran de manera clara en la vista. El backend fue implementado con Node.js y se subió a la plataforma Onrender, lo que permite la gestión eficiente de las solicitudes de validación de certificados, asegurando una integración fluida con el sistema de generación de QR y la base de datos asociada.",
    bannerImage: "/api.png",
    category: "Desarrollo web",
    videoUrl: "https://www.youtube.com/watch?v=qCcQkMIxCt0?modestbranding=1&rel=0",
  },

  {
    id: 6,
    title: "Todo List",
    technologies: ["React"],
    code: "Público",
    demoLink: "https://react-todos-jmqp.vercel.app/",
    description:"Desarrollo de una aplicación de lista de tareas (Todo List App) utilizando el framework React. La aplicación permite a los usuarios gestionar sus tareas pendientes o por realizar de manera eficiente e intuitiva.",
    githubLink: "https://github.com/T0ny-dev/react_todos",
    bannerImage: "/todo.png",
    category: "Desarrollo web",
    videoUrl: "https://www.youtube.com/watch?v=6bSP5lcPF98?modestbranding=1&rel=0",
  },
  {
    id: 7,
    title: "CRUD",
    technologies: ["React", "CSS", "Firebase"],
    code: "Público",
    demoLink: "https://siu-utbc.vercel.app/",
    description:"Desarrollo de un sistema de gestión de información escolar (CRUD) utilizando React y Firebase. El sistema permite a los usuarios realizar operaciones de creación, lectura, actualización y eliminación de datos de estudiantes, profesores y cursos, proporcionando una interfaz amigable y funcional para la gestión de la información escolar.",
    githubLink: "https://github.com/T0ny-dev/SIU-Sistema-Escolar",
    bannerImage: "/CRUD.png",
    category: "Desarrollo web",
    videoUrl: "https://www.youtube.com/watch?v=oy54xST-m1E?modestbranding=1&rel=0",
  },
  {
    id: 8,
    title: "Pokedex",
    technologies: ["React", "CSS", "API"],
    code: "Público",
    demoLink: "https://04-js-launch-x-latam.netlify.app/",
    description:"Desarrollo de una Pokedex utilizando JavaScript y consumiendo una API de Pokemon. La Pokedex permite a los usuarios buscar y visualizar información detallada de los diferentes Pokemon, incluyendo su nombre, tipo, habilidades y estadísticas.",
    githubLink: "https://github.com/T0ny-dev/MisionFrontEnd-Launch-X-Latam/tree/main/04-JS",
    bannerImage: "/pokemon.png",
    category: "Desarrollo web",
    videoUrl: "https://www.youtube.com/watch?v=5PP24sgDOSw?modestbranding=1&rel=0",
  },
  {
    id: 9,
    title: "Magic 8",
    technologies: ["JS", "CSS", ],
    code: "Público",
    demoLink: "https://t0ny-dev.github.io/Magic_8_ball/",
    githubLink: "https://github.com/T0ny-dev/Magic_8_ball",
    description:"Desarrollo de una aplicación de Magic 8 Ball utilizando JavaScript. La aplicación simula el funcionamiento de una bola mágica que responde a las preguntas de los usuarios con respuestas aleator",
    bannerImage: "/8.JPG",
    category: "Desarrollo web",
    videoUrl: "https://www.youtube.com/watch?v=et3huX8mc0Y?modestbranding=1&rel=0",
  },
  {
    id: 10,
    title: "Servidor con Node.js",
    technologies: ["JS", "Node", "Express", "API"],
    code: "Público",
    githubLink: "https://github.com/T0ny-dev/servidor-y-API-con-NODEJS",
    description:"Desarrollo de un servidor con Node.js y Express, que permite obtener listado de cursos",
    bannerImage: "/node.JPG",
    category: "Desarrollo web",
    videoUrl: "https://www.youtube.com/watch?v=zAC-B8YEknU?modestbranding=1&rel=0",
  },
  {
    id: 11,
    title: "Pokemon API",
    technologies: ["React", "CSS", "API"],
    code: "Público",
    demoLink: "https://react-introduccion-ten.vercel.app/",
    githubLink: "https://github.com/T0ny-dev/react_introduccion",
    description:"Desarrollo de cards consumiendo una API de Pokemon. La aplicación obtiene los primero 151 pokemones y los muestra en cards con su nombre y tipo",
    bannerImage: "/pokeapi.JPG",
    category: "Desarrollo web",
    videoUrl: "https://www.youtube.com/watch?v=50gL4oknTXE?modestbranding=1&rel=0",
  },
  {
    id: 12,
    title: "Wheater API",
    technologies: ["JS", "CSS", "API"],
    code: "Público",
    demoLink: "https://t0ny-dev.github.io/api_weather_js/",
    githubLink: "https://github.com/T0ny-dev/api_weather_js",
    description:"Desarrollo de una aplicación que consume una API de clima. La aplicación permite al usuario buscar el clima de una ciudad y muestra la temperatura, humedad y descripción del clima",
    bannerImage: "/weather.JPG",
    category: "Desarrollo web",
    videoUrl: "https://www.youtube.com/watch?v=wcHW5L0xdRg?modestbranding=1&rel=0",
  },
  {
    id: 13,
    title: "Generador de GIF con python",
    technologies: ["Python", ],
    code: "Público",
    githubLink: "https://github.com/T0ny-dev/GIF_Python_generator",
    description:"Desarrollo de un generador de gif con Python. el programa trabaja con imagenes para convertirlas en formato GIF",
    bannerImage: "/gif.JPG",
    category: "Desarrollo web",
    videoUrl: "https://www.youtube.com/watch?v=nM7MlDgcBJ4?modestbranding=1&rel=0",
  },
  {
    id: 14,
    title: "Fake API Store",
    technologies: ["React", "CSS", "Firebase"],
    code: "Público",
    demoLink: "https://fake-store-api-woad-three.vercel.app/",
    githubLink: "https://github.com/T0ny-dev/Fake-Store-API",
    description:"Desarrollo de una tienda online con React y fake store API. La aplicación consume una API de productos y muestra los productos en cards con su nombre, precio y descripción",
    bannerImage: "/store.JPG",
    category: "Desarrollo web",
    videoUrl: "https://www.youtube.com/watch?v=v5hSBumxqMY?modestbranding=1&rel=0",
  },
  {
    id: 15,
    title: "Blog Dev.to",
    technologies: ["React", "CSS", "Firebase"],
    code: "Público",
    demoLink: "https://03-css-lauch-x-latam.netlify.app/",
    githubLink: "https://github.com/T0ny-dev/Blog-Dev.to",
    description:"Desarrollo de un blog con React La aplicación consume una API de Dev.to y muestra los blogs en cards con su titulo, autor y fecha de publicación",
    bannerImage: "/blog.JPG",
    category: "Desarrollo web",
    videoUrl: "https://www.youtube.com/watch?v=VLp1DwgYlGg?modestbranding=1&rel=0",
  },
  {
    id: 16,
    title: "Sitio web Vaccines",
    technologies: ["HTML", "CSS", ],
    code: "Público",
    demoLink: "https://03-css-lauch-x-latam.netlify.app/",
    githubLink: "https://github.com/T0ny-dev/MisionFrontEnd-Launch-X-Latam/tree/main/03-CSS",
    description:"Desarrollo de un sitio web de vacunas con HTML y CSS. El sitio web muestra información sobre las vacunas y su importancia",
    bannerImage: "/vaccine.JPG",
    category: "Sitios web",
    videoUrl: "https://www.youtube.com/watch?v=Aaa7xdJcy2U?modestbranding=1&rel=0",
  },
  {
    id: 17,
    title: "donuts website",
    technologies: ["HTML", "CSS"],
    code: "Público",
    demoLink: "https://02-html-launch-x-latam.netlify.app/",
    githubLink: "https://github.com/example/portfolio",
    description:"Desarrollo de un sitio web de donas con HTML y CSS. El sitio web muestra información.",
    bannerImage: "/donut.JPG",
    category: "Sitios web",
    videoUrl: "https://youtu.be/J-CgGIoVxUI?modestbranding=1&rel=0",
  },
  {
    id: 18,
    title: "Agencia Nexus",
    technologies: ["React", "CSS", "NEXTJS"],
    code: "Público",
    demoLink: "https://agencianexusmarketing.com/",
    githubLink: "https://github.com/T0ny-dev/Nexus_Marketing_Website",
    description:"Desarrollo de un sitio web para la agencia Nexus Marketing con NextJS El sitio web muestra información sobre la agencia y sus servicios",
    bannerImage: "/nexus.JPG",
    category: "Sitios web",
    videoUrl: "https://youtu.be/-j2X6evHlJs?modestbranding=1&rel=0",
  },
  {
    id: 19,
    title: "LarnU Login",
    technologies: ["HTML", "CSS", ],
    code: "Público",
    githubLink: "https://github.com/T0ny-dev/larnU_login",
    description:"Desarrollo de un login de LarnU con HTML y CSS. El login muestra información sobre la plataforma y permite a los usuarios ingresar",
    bannerImage: "/larnulog.JPG",
    category: "Sitios web",
    videoUrl: "https://youtu.be/h_1d6rf745w?modestbranding=1&rel=0",
  },
  {
    id: 20,
    title: "Runran website",
    technologies: ["HTLM", "CSS", ],
    code: "Público",
    demoLink: "https://t0ny-dev.github.io/proyecto_final_html_css/",
    githubLink: "https://github.com/T0ny-dev/proyecto_final_html_css",
    description:"Desarrollo de un sitio web de Runran con HTML y CSS. El sitio web muestra información sobre la empresa y sus servicios",
    bannerImage: "/run.JPG",
    category: "Sitios web",
    videoUrl: "https://www.youtube.com/watch?v=iCuy3HAq3pk?modestbranding=1&rel=0",
  },
  {
    id: 21,
    title: "CANACINTRA website",
    technologies: ["React", "CSS", "ASTRO"],
    code: "Público",
    demoLink: "https://www.canacintratexas.com/",
    githubLink: "https://github.com/T0ny-dev/cacintra-texas",
    description:"Desarrollo de un sitio web de CANACINTRA con React y Astro. El sitio web muestra información sobre la empresa y sus servicios",
    bannerImage: "/cana.JPG",
    category: "Sitios web",
    videoUrl: "https://www.youtube.com/watch?v=JKjj9vUM-Lc?modestbranding=1&rel=0",
  },
  {
    id: 22,
    title: "CICADE",
    technologies: ["PHP", "wordpress", "Leanrdash", "CSS", "zapier"],
    code: "Público",
    demoLink: "https://cicade.network/",
    description:"Desarrollo de un sitio web de CICADE con PHP y Wordpress. El sitio web muestra información sobre la empresa y sus servicios, cuenta con plataforma interna de cursos y IA",
    bannerImage: "/cicade.JPG",
    category: "Sitios web",
    videoUrl: "https://www.youtube.com/watch?v=00IVf-T3cHg?modestbranding=1&rel=0",
  },
  {
    id: 23,
    title: "Ricardo Botello",
    technologies: ["NEXTJS", "CSS",],
    code: "Público",
    demoLink: "https://www.ricardobotello.mx/",
    description:"Desarrollo de un sitio web de Ricardo Botello con NextJS. El sitio web muestra información sobre el autor y sus servicios",
    bannerImage: "/ric.JPG",
    category: "Sitios web",
    videoUrl: "https://youtu.be/QhJkZAhPQqE?modestbranding=1&rel=0",
  },
  {
    id: 24,
    title: "Jobbi",
    technologies: ["Figma", "PS", "AI"],
    code: "Público",
    demoLink: "https://www.behance.net/gallery/125447657/JOBBi-Web-App-to-find-a-job-UXUI?tracking_source=search_projects_appreciations|jobbi&l=0",
    description:"Desarrollo de un diseño de la aplicación Jobbi con Figma, Photoshop y Illustrator. El diseño muestra la interfaz de usuario y la experiencia de usuario de la aplicación",
    bannerImage: "/job.JPG",
    category: "Proyectos",
    videoUrl: "https://youtu.be/_ku6xH_IRzU?modestbranding=1&rel=0",
  },
  {
    id: 25,
    title: "Bym group",
    technologies: ["Figma", "PS", "AI"],
    code: "Público",
    demoLink: "https://www.behance.net/gallery/128282697/bymGroup-branding-and-web-design",
    description:"Desarrollo de un diseño de la empresa Bym Group con Figma, Photoshop y Illustrator. El diseño muestra la identidad visual de la empresa y su sitio web",
    bannerImage: "/bymg.JPG",
    category: "Proyectos",
    videoUrl: "https://youtu.be/g-is2Vm9H6U?modestbranding=1&rel=0",
  },
  {
    id: 26,
    title: "Tekton",
    technologies: ["Figma", "PS", "AI"],
    code: "Público",
    demoLink: "https://www.behance.net/gallery/134671939/Tekton-Tech-diseno-de-marca",
    description:"Desarrollo de un diseño de la empresa Tekton con Figma, Photoshop y Illustrator. El diseño muestra la identidad visual de la empresa y su sitio web",
    bannerImage: "/tekton.JPG",
    category: "Proyectos",
    videoUrl: "https://youtu.be/TBpuxiqTzUM?modestbranding=1&rel=0",
  },
  {
    id: 27,
    title: "LMS Business Center",
    technologies: ["Figma", "Learnworlds",],
    code: "Privado",
    description:"Desarrollo de un diseño de la plataforma LMS Business Center con Figma y Learnworlds. El diseño muestra la interfaz de usuario y la experiencia de usuario de la plataforma",
    bannerImage: "/bc.JPG",
    category: "Proyectos",
    videoUrl: "https://youtu.be/49Pp6d1RlE4?modestbranding=1&rel=0",
  },
  {
    id: 28,
    title: "Kiosko de servicios",
    technologies: ["Figma", "React", "Firebase"],
    code: "Privado",
    description:"Desarrollo de un diseño de un kiosko de servicios con Figma, React y Firebase. El diseño muestra la interfaz de usuario y la experiencia de usuario del kiosko",
    bannerImage: "/kiosko.JPG",
    category: "Proyectos",
    videoUrl: "https://youtu.be/16yxjZT_YCE?modestbranding=1&rel=0",
  },
  {
    id: 29,
    title: "Abogabot",
    technologies: ["PS", "AI", "Figma"],
    code: "Público",
    githubLink: "https://github.com/T0ny-dev/MisionFrontEnd-Launch-X-Latam/tree/main/01-INTRO",
    description:"Desarrollo de un diseño de la aplicación Abogabot con Photoshop, Illustrator y Figma. El diseño muestra la interfaz de usuario y la experiencia de usuario de la aplicación",
    bannerImage: "/abogabot.svg",
    category: "Proyectos",
    videoUrl: "https://youtu.be/VtUfkDWMSSQ?modestbranding=1&rel=0",
  },
  {
    id: 30,
    title: "Diseno de Gamificacion",
    technologies: ["Figma",],
    code: "Público",
    description:"Desarrollo de un diseño de gamificación con Figma. El diseño muestra la interfaz de usuario y la experiencia de usuario de la gamificación",
    bannerImage: "/gam.JPG",
    category: "Proyectos",
    videoUrl: "https://youtu.be/lsHxhkO2i3o?modestbranding=1&rel=0",
  },
  {
    id: 31,
    title: "Laborcamp Hackathon",
    technologies: ["React", "CSS", "Firebase"],
    code: "Público",
    description:"Desarrollo de un diseño de la aplicación Laborcamp Hackathon con React, CSS y Firebase. El diseño muestra la interfaz de usuario y la experiencia de usuario de la aplicación",
    bannerImage: "/labor.JPG",
    category: "Proyectos",
    videoUrl: "https://youtu.be/GnpKjPRnxyE?modestbranding=1&rel=0",
  },
  {
    id: 32,
    title: "Tablero de ingenieria KPIS",
    technologies: ["Google Sheets", "Looker Studio",],
    code: "Público",
    demoLink: "https://lookerstudio.google.com/s/sOLVkSN-0k0",
    description:"Desarrollo de un tablero de ingeniería KPIS con Google Sheets y Looker Studio. El tablero muestra información sobre los KPIS de ingeniería",
    bannerImage: "/ing.JPG",
    category: "Analisis de datos",
    videoUrl: "https://youtu.be/MkftQ-JKtgY?modestbranding=1&rel=0",
  },

  {
    id: 33,
    title: "Encuestas generadas en Survey JS",
    technologies: ["SurveyJS",],
    code: "Privado",
    description:"Desarrollo de encuestas generadas en Survey JS. Las encuestas permiten a los usuarios responder preguntas y obtener resultados",
    bannerImage: "/sur.JPG",
    category: "Analisis de datos",
    videoUrl: "https://www.youtube.com/watch?v=y1cmGkSXamc?modestbranding=1&rel=0",
  },
  {
    id: 34,
    title: "Qira website",
    technologies: ["HTML", "css"],
    code: "Público",
    description:"Desarrollo de un sitio web de Qira con HTML y CSS. El sitio web muestra información sobre la empresa y sus servicios",
    bannerImage: "/qira.png",
    githubLink:"https://github.com/T0ny-dev/qira-workspace",
    demoLink:"https://qira-workspace.vercel.app/",
    category: "Sitios web",
    videoUrl: "https://youtu.be/gneamZBsvgw?modestbranding=1&rel=0",
  },
  {
    id: 35,
    title: "Campus Virtual",
    technologies: ["Lua", "Rotblox"],
    code: "Privado",
    description:"Desarrollo de un campus virtual en Roblox con Lua. El campus virtual permite a los usuarios interactuar y aprender en un entorno virtual",
    bannerImage: "/ut.png",
    category: "Proyectos",
    videoUrl: "https://www.youtube.com/watch?v=UrFUmIq_6LY&t=18s?modestbranding=1&rel=0",
  },
  {
    id: 36,
    title: "Academia Virtual",
    technologies: ["Wordpress", "Elementor", "CSS", "PHP"],
    code: "Privado",
    description:"Desarrollo de una academia virtual con Wordpress y Elementor. La academia virtual permite a los usuarios acceder a cursos y contenido educativo",
    bannerImage: "/akd.PNG",
    category: "Proyectos",
    videoUrl: "https://www.youtube.com/watch?v=YbNEeP1X5gU?modestbranding=1&rel=0",
  },
  {
    id: 37,
    title: "List App Flutter",
    technologies: ["Flutter", "Dart"],
    code: "Público",
    description:"Desarrollo de una aplicación de lista de palabras con Flutter y Dart. La aplicación permite a los usuarios elegir una palabra de una lista y guardarla en una lista de favoritos",
    bannerImage: "/flutter.png",
    githubLink:"https://github.com/T0ny-dev/List-App-Flutter",
    category: "Desarrollo web",
    videoUrl: "https://www.youtube.com/watch?v=SBq2OkgHkwg?modestbranding=1&rel=0",
  }

  
  
  
  
  // Más proyectos...
];

export default projects;
